// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fail-fast com mensagem visível em vez de tela preta silenciosa.
// Sem env vars, createClient retorna um client quebrado que crasha no
// primeiro request — bloqueando o render do React inteiro.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  if (typeof document !== 'undefined') {
    document.body.innerHTML = `
      <div style="padding:32px;font-family:system-ui;color:#e0e0e0;background:#05050a;min-height:100vh;">
        <h1 style="color:#ff5a5f;margin:0 0 16px;">⚠ Configuração ausente</h1>
        <p>As variáveis <code>VITE_SUPABASE_URL</code> e <code>VITE_SUPABASE_PUBLISHABLE_KEY</code> não estão configuradas no Vercel.</p>
        <p style="color:#888;font-size:14px;">URL: <code>${SUPABASE_URL || '(vazio)'}</code></p>
        <p style="color:#888;font-size:14px;">Key: <code>${SUPABASE_PUBLISHABLE_KEY ? '(setada)' : '(vazio)'}</code></p>
        <p>Configure as env vars no painel do Vercel e re-deploy.</p>
      </div>`;
  }
  throw new Error('Missing Supabase env vars (VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY)');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});